import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { cookies } from "next/headers"
import { StoreProvider } from "@/store/store-provider";
import LayoutBasedOnAuth from "./layout-basedon-auth";
import AuthenticatedLayout from "./authenticated-layout";
import { Toaster } from "@/components/ui/toaster"
import { SidebarProvider } from "@/components/ui/sidebar";


const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = await cookies();
  const defaultOpen = cookieStore.get("sidebar:state")?.value === "true";

  return (
    <StoreProvider>
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <SidebarProvider defaultOpen={defaultOpen}>
            <LayoutBasedOnAuth>
              <AuthenticatedLayout defaultOpen={defaultOpen}>{children}</AuthenticatedLayout>
            </LayoutBasedOnAuth>
          </SidebarProvider>
          <Toaster />
        </body>
      </html>
    </StoreProvider>
  );
}
